Update tank application
industrial-edge/miscellaneous pull request #18
Opened 2023-04-20 10:51 UTC by EvaKaul

- new parameter for batch ID
- new parameter for gas consumption
- new parameter for project information

2023-04-20 10:53 UTC, EvaKaul commented
Hi @j0hannesfr, may you could review these changes within the tank application (docu in Readme.md and TIA project). Thanks a lot in advance!

2023-04-24 12:29 UTC, j0hannesfr requested changes
Please reset the 2 new parameters together with everything else in FB2_Filling Network 5 to make it consistent

2023-04-24 12:29 UTC, j0hannesfr commented on tank application/tia-tank-application.zap16
batchID and gasConsumptionHeatingTank doesn't get reset with the reset trigger

2023-05-02 12:14 UTC, EvaKaul reviewed
made changes according to review

2023-05-03 06:26 UTC, EvaKaul commented
@j0hannesfr, thanks for the review! Please check my fixes in tia-tank-application.zap16 and finish the review. Afterwards I can merge the code.

2023-05-03 08:53 UTC, j0hannesfr approved these changes
Thanks Eva, everything looks fine now!

2023-05-03 09:17 UTC, merged